/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CityBuilding } from './types';

export const INITIAL_CITY_BUILDINGS: CityBuilding[] = [
  {
    id: 'bld-core',
    name: 'ATP Core Lab',
    tagline: 'Deep AI & Kernel Optimizers',
    category: 'Deep Tech & AI',
    founder: 'Nagesh Bandi',
    description: 'Constructing high-performance logical models and system-level compilers to deploy generative code systems natively on local edges.',
    growth: 88,
    isComingSoon: false,
    gridX: -1.8,
    gridZ: 1.8,
    height: 3.6,
    color: '#ff6a00', // Neon Orange
  },
  {
    id: 'bld-logistics',
    name: 'Corridor Autonomous',
    tagline: 'The Bangalore-ATP Transit Stack',
    category: 'Robotics & Logistics',
    founder: 'Priya Anant',
    description: 'Developing autonomous route telemetry systems specifically calibrated for heavy logistic transit corridors spanning South Indian tech capitals.',
    growth: 72,
    isComingSoon: false,
    gridX: 1.8,
    gridZ: -1.8,
    height: 2.2,
    color: '#00ccff', // Cyber Blue
  },
  {
    id: 'bld-agri',
    name: 'Silicon AgriNode',
    tagline: 'Microclimatic Irrigation Compilers',
    category: 'Climate & Agritech',
    founder: 'Rami Reddy',
    description: 'Synthesizing IoT wind-patterns and soil telemetry data to automate drip arrays across semi-arid terrains, reducing water spend by massive margins.',
    growth: 65,
    isComingSoon: false,
    gridX: -3.2,
    gridZ: -3.2,
    height: 1.8,
    color: '#00ff66', // Laser Green
  },
  {
    id: 'bld-wind',
    name: 'Rayalaseema WindGrid',
    tagline: 'Generative Wind Core Sinks',
    category: 'Clean Energy',
    founder: 'Soma Sekhar',
    description: 'Architecting algorithmic dispatch engines to capture and channel energy surges from wind corridor tunnels of Rayalaseema into national grid nodes.',
    growth: 92,
    isComingSoon: false,
    gridX: 3.2,
    gridZ: 3.2,
    height: 3.0,
    color: '#ffa500', // Amber
  },
  {
    id: 'bld-fin',
    name: 'Stealth FinCore',
    tagline: 'Global Ledger Settlement Nodes',
    category: 'Fintech & Web3',
    founder: 'Vikram Gupta',
    description: 'Deploying robust cryptographic settlement routes enabling rural micro-enterprises to collect international payouts instantly with low basis points.',
    growth: 81,
    isComingSoon: false,
    gridX: 3.5,
    gridZ: -1.2,
    height: 3.2,
    color: '#ff00ff', // Cyber Pink
  },
  {
    id: 'bld-devs',
    name: 'HyperScale Devs',
    tagline: 'AI Orchestrated Tech Factories',
    category: 'SaaS & Dev Tools',
    founder: 'Amulya K.',
    description: 'Structuring remote developer sandboxes backed by automated AI copilots, allowing top global scaleouts to assemble engineering teams at light speed.',
    growth: 95,
    isComingSoon: false,
    gridX: 1.2,
    gridZ: 1.2,
    height: 4.4,
    color: '#ffffff', // Cyber White
  },
  {
    id: 'bld-edtech',
    name: 'Anantaya XR',
    tagline: 'Spatial Immersive Classrooms',
    category: 'AR/VR & Education',
    founder: 'Dr. Girish Lal',
    description: 'Broadcasting low-bandwidth WebXR mechanical simulations to technical colleges to elevate vocational competency matrices in heavy assembly.',
    growth: 58,
    isComingSoon: false,
    gridX: -3.8,
    gridZ: 1.2,
    height: 1.9,
    color: '#ff3300', // Hot Red
  },
  {
    id: 'bld-cyber',
    name: 'Aegis Hash',
    tagline: 'Dynamic Firmware Encryptors',
    category: 'Cybersecurity',
    founder: 'Karthik S.',
    description: 'Providing dynamic polymorphic shields to protect critical industrial telemetry grids and power dispatch nodes from zero-day vectors.',
    growth: 76,
    isComingSoon: false,
    gridX: -1.2,
    gridZ: -1.2,
    height: 2.6,
    color: '#ca1111', // Crimson Red
  },
  // ----- COMING SOON STEALS -----
  {
    id: 'bld-soon-health',
    name: 'TeleHealth Orbit',
    tagline: 'Satellite Low-Latency Diagnostics',
    category: 'Healthtech',
    founder: 'TBD',
    description: 'Preparing to launch modular low-orbit satellite receptor dishes connecting nomadic regions with direct AI surgical advice.',
    growth: 0,
    isComingSoon: true,
    gridX: 2.0,
    gridZ: 4.0,
    height: 1.2,
    color: '#555555', // Muted Gray
  },
  {
    id: 'bld-soon-foundry',
    name: 'Robotic Foundry',
    tagline: 'Autonomous Heavy Metal Sinks',
    category: 'Smart Manufacturing',
    founder: 'TBD',
    description: 'Architecting fully automated, zero-carbon precision casting foundries powered by green grid reserves.',
    growth: 0,
    isComingSoon: true,
    gridX: -2.0,
    gridZ: -4.0,
    height: 1.4,
    color: '#555555',
  },
  {
    id: 'bld-soon-quantum',
    name: 'ATP Quantum Nodes',
    tagline: 'Cryogenic Josephson Compilers',
    category: 'Quantum Computing',
    founder: 'TBD',
    description: 'Coordinating blueprints for local cryogenic computing chambers enabling instant cryptography modeling.',
    growth: 0,
    isComingSoon: true,
    gridX: 4.0,
    gridZ: 4.0,
    height: 1.1,
    color: '#555555',
  },
  {
    id: 'bld-soon-space',
    name: 'SpaceJet Aero',
    tagline: 'Atmospheric Drag Compressors',
    category: 'Aerospace',
    founder: 'TBD',
    description: 'Developing high-altitude wing surfaces designed to reduce frictional index of low orbit communication probes.',
    growth: 0,
    isComingSoon: true,
    gridX: -4.0,
    gridZ: -4.0,
    height: 1.5,
    color: '#555555',
  }
];
